### ISSUE TITLE
Song Lyrics

### ISSUE THREAD

**Issue by nikobix** [ferferga/MMM-GoogleCast#15]
Hi Ferferga

I am looking at integrating lyrics to my MM, and currently have lyrics displayed depending on what is playing on your GoogleCast Module (with a little modification -  added a sendNotification to send the media payload which is picked up in LyricTime).

Just wanted to know if there were any time signals that could be transferred. i.e. position in track, mins/secs or just secs with the length of the track.

I am just no good with Python, so cannot work out how to extract this info.

Any ideas?

Current module is  - https://github.com/nikobix/MMM-LyricTime

Cheers

Nikobix

**Comment by ferferga** [comment]
@nikobix Hello!

Can you make a PR with the notifications code so, whenever I take a look at it, I can add that data to the payload?

Thanks!

**Comment by ferferga** [comment]
@nikobix Not sure if you're closing the PRs because you are having trouble with them.

A quick help:

First of all, you must update your fork. You're committing to an old commit in an old branch. You can do it by deleting your fork and forking again or by adding this repo as upstream:

(In your cloned repo):
```
git remote add upstream https://github.com/ferferga/MMM-GoogleCast
git fetch upstream
git rebase upstream/master

```

That will update your repo to the latest commit. Take in mind that this will overwrite any changes you have made locally if you didn't commit them. So make sure you commit them first.

If you don't want to use git locally, just drag and drop your file to the main page of this repo and it would automatically create a branch in your fork with your changes, but based in the latest commit.

Don't hesitate in ask me if doubt.

**Comment by nikobix** [comment]
Hi Fernando
I think I finally worked out git hub. New to all this collaborative programming.
Let me know if you now see my pill.
Thanks
Nik

**Comment by ferferga** [comment]
@nikobix Yes, I see it now! Hope you end up enjoying it! 😊

I'll check it once I get to my computer.

Btw, you can always check which lines were changed compared to the branch you're trying to merge to (in this case ``master``) if you go to the **Changed files** tab in any PR: [See here](https://github.com/ferferga/MMM-GoogleCast/pull/19/files)

**Comment by nikobix** [comment]
Cheers
