### ISSUE TITLE
Multiple Devices

### ISSUE THREAD

**Issue by Theman2051** [ferferga/MMM-GoogleCast#3]
Hey Fernando,
I am currently setting up my new Magic Mirror and was wondering if there is anyway to add multiple devices using your MMM-GoogleCast module. I have 5 Google Minis, an Nvidia Shield and a castable tv. Could the module scan the network for any casting device and display which one is casting or monitor multiple devices IDs?

**Comment by ferferga** [comment]
@Theman2051 Good afternoon!

Sincerely, I'm not sure how it will work. I encourage you to test and tell me how it works in your scenario (I don't have that many groups/devices) so I can have a better idea on how I can improve it (if it works, maybe it doesn't). 

You should start this by creating multiple copies of the module section in config.js (changing the device ID of course). I expect the two instances to show the same content or be confused with the multiple devices, but no way to know unless we test it (like when we launched humans to the moon, it's an experiment that only can be achieved by trying! :D).
Don't forget to tell me how this works, please.

As for "showing the device and display the one which is casting", I think that you mean something like discussed in #2 . I didn't have the time to update the module accordingly because I've been out in vacation, but I'm now getting back to the routine, so stay tuned for new things soon!

Have a nice day!

**Comment by Theman2051** [comment]
@ferferga Good Afternoon,

I tested multiple modules earlier and it does not seem to work. I tried play on only one if the devices and on both of them. I also used a group ID with a single ID that is in that group and it didn't work either. It's seems to only be able to scan a single source at a time. If there is anything I can do to help or anything you need tested please let me know.

**Comment by ferferga** [comment]
@Theman2051 What happens exactly when you duplicate the module lines in config.js? The multiple instances show the same content from one source repeated multiple times, right?

**Comment by Theman2051** [comment]
@ferferga When I copy the module lines and change the device ID both modules load. However no mater what I play or what I play it on neither show anything. They both appear as if nothing is playing.

**Comment by ferferga** [comment]
Closing, as this has been finally implemented in MMM-GoogleCast 2.0.

See the changelog and instructions for updating your installation in the [Releases](https://github.com/ferferga/MMM-GoogleCast/releases/tag/2.0) tab.
